
services:
  - type: web
    name: lithology-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt && cd frontend && npm install && chmod +x node_modules/.bin/react-scripts && npm run build"
    startCommand: "gunicorn backend.api:app"
    plan: free
    regions: global
    envVars:
      - key: FLASK_ENV
        value: production
