
services:
  - type: web
    name: lithology-backend
    env: python
    buildCommand: "pip install -r requirements.txt && cd backend/frontend && npm install && npm run build"
    startCommand: "gunicorn api:app"
    plan: free
    regions: global
    envVars:
      - key: FLASK_ENV
        value: production
